### ISSUE TITLE
Add more tests

### ISSUE THREAD

**Issue by alexnorell** [alexnorell/emojyo#7]

**Comment by ColePBryan** [comment]
Some tests we might want to add:
- Create same user name twice
- Create empty string user name
- Send Emojyo to Non-existent user
- Send Emojyo to Self
- Get list of Emojyo's twice (based on our planned implementation this should get an empty list the second time?)

Can you think of any others?

**Comment by ColePBryan** [comment]
Closing this issue as too vague. Opened issue #10 #11 #12 #13 and #14 as possible tests to add. We can open new issues for any other tests we feel we need.
